--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/alexbgameson/3.0.0Alpha10-PocketMine-PluginsV2
branches:
- master
projects:
  FormAPI:
    path: FormAPI/
  ReportUI:
    path: ReportUI/
...
